<?php

// Voxb Errors:
  define('CONTENTTYPES_MISSING', 1);
  define('COULD_NOT_CREATE_DATA_USERID_DID_NOT_EXIST', 2);
  define('COULD_NOT_CREATE_USER', 3);
  define('COULD_NOT_FIND_ITEM', 4);
  define('COULD_NOT_FIND_ITEM_FOR_USER', 5);
  define('COULD_NOT_FIND_ITEMS', 6);
  define('COULD_NOT_FIND_OBJECT', 7);
  define('COULD_NOT_FIND_OBJECT_ORPHANED_ITEMS_SHOULD_BE_DELETED', 8);
  define('COULD_NOT_FIND_USER', 9);
  define('COULD_NOT_LOCATE_USER_WITH_GIVEN_FINGERPRINT', 10);
  define('EMPTY_QUALIFIER', 11);
  define('EMPTY_SEARCHSTRING', 12);
  define('ERROR_DELETING_ITEM_FROM_DATABASE', 13);
  define('ERROR_DELETING_USER_FROM_DATABASE', 14);
  define('ERROR_FETCHING_ITEM_FROM_DATABASE', 15);
  define('ERROR_FETCHING_ITEMS_FROM_DATABASE', 16);
  define('ERROR_FETCHING_LOCALS_DATA_FROM_DATABASE', 17);
  define('ERROR_FETCHING_OBJECT_FROM_DATABASE', 18);
  define('ERROR_FETCHING_REVIEW_DATA_FROM_DATABASE', 19);
  define('ERROR_FETCHING_USER_FROM_DATABASE', 20);
  define('ERROR_INSERTING_COMPLAINT_INTO_DATABASE', 21);
  define('ERROR_INSERTING_ITEM_IN_DATABASE', 22);
  define('ERROR_INSERTING_LOCALS_IN_DATABASE', 23);
  define('ERROR_INSERTING_OBJECT_IN_DATABASE', 24);
  define('ERROR_INSERTING_REVIEW_IN_DATABASE', 25);
  define('ERROR_INSERTING_TAGS_IN_DATABASE', 26);
  define('ERROR_UNDELETING_ITEM_FROM_DATABASE', 27);
  define('ERROR_UNDELETING_USER_FROM_DATABASE', 28);
  define('ERROR_UPDATING_ITEMS_IN_DATABASE', 29);
  define('ERROR_UPDATING_LOCALS_IN_DATABASE', 30);
  define('ERROR_UPDATING_OBJECTS_IN_DATABASE', 31);
  define('ERROR_UPDATING_REVIEW_IN_DATABASE', 32);
  define('ERROR_UPDATING_TAGS_IN_DATABASE', 33);
  define('FINGERPRINT_NOT_VALID', 34);
  define('FOUND_NO_ITEM_FROM_GIVEN_VOXBIDENTIFIER', 35);
  define('NO_FIELDS_TO_UPDATE', 36);
  define('NO_ITEMS_OR_OBJECTS_TO_FETCH', 37);
  define('NO_USER_FOUND_WITH_GIVEN_ID', 38);
  define('QUALIFIER_NOT_YET_IMPLEMENTED', 39);
  define('UNKNOWN_QUALIFIER', 40);
  define('USERID_INVALID_MUST_BE_AN_INTEGER', 41);
  define('VOXBIDENTIFIER_INVALID_MUST_BE_AN_INTEGER', 42);
  define('USER_ALREADY_EXISTS', 43);
  define('AUTHENTICATION_ERROR', 44);
  define('COULD_NOT_REACH_DATABASE', 45);
  define('NO_USER_FOUND_WITH_GIVEN_FINGERPRINT', 46);

// Voxb Qualifiers:
  define('QUALIFIER_VOXB', 1);
  define('QUALIFIER_LOCAL', 2);
  define('QUALIFIER_EAN', 3);
  define('QUALIFIER_ISBN', 4);
  define('QUALIFIER_ISSN', 5);
  define('QUALIFIER_TAG', 6);
  define('QUALIFIER_TITLE', 7);
  define('QUALIFIER_CONTRIBUTOR', 8);
  define('QUALIFIER_TIMESTAMPMIN', 9);
  define('QUALIFIER_TIMESTAMPMAX', 10);
  define('QUALIFIER_USERID', 11);

?>