--------------------------------------------------------
--  File created - Thursday-October-20-2011   
--------------------------------------------------------
  DROP TABLE "MKR"."VOXB_COMPLAINTS";
  DROP TABLE "MKR"."VOXB_INSTITUTIONS";
  DROP TABLE "MKR"."VOXB_ITEMS";
  DROP TABLE "MKR"."VOXB_LOCALS";
  DROP TABLE "MKR"."VOXB_LOGS";
  DROP TABLE "MKR"."VOXB_OBJECTS";
  DROP TABLE "MKR"."VOXB_REVIEWS";
  DROP TABLE "MKR"."VOXB_TAGS";
  DROP TABLE "MKR"."VOXB_USERS";
  DROP SEQUENCE "MKR"."VOXB_COMPLAINTS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_ITEMS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_LOCALS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_LOGS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_OBJECTS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_REVIEWS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_TAGS_SEQ";
  DROP SEQUENCE "MKR"."VOXB_USERS_SEQ";
--------------------------------------------------------
--  DDL for Sequence VOXB_COMPLAINTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_COMPLAINTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6907 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_LOCALS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_LOCALS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 220 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_LOGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_LOGS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 452649 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_OBJECTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_OBJECTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1613 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_REVIEWS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_REVIEWS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4042 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_TAGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_TAGS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 5260 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOXB_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MKR"."VOXB_USERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3515 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table VOXB_COMPLAINTS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_COMPLAINTS" 
   (	"COMPLAINTID" NUMBER, 
	"OFFENDER_INSTITUTIONNAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"OFFENDER_USERID" NUMBER, 
	"OFFENDING_ITEMID" VARCHAR2(32 BYTE), 
	"COMPLAINANT_USERID" NUMBER, 
	"STATUS" VARCHAR2(16 BYTE), 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"OFFENDER_INSTITUTIONID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_INSTITUTIONS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_INSTITUTIONS" 
   (	"INSTITUTIONNAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CONTACTPERSON_NAME" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"CONTACTPERSON_EMAIL" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CONTACTPERSON_PHONE" NUMBER(8,0) DEFAULT NULL, 
	"MODERATOR_NAME" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"MODERATOR_EMAIL" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"INSTITUTIONID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_ITEMS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_ITEMS" 
   (	"ITEMIDENTIFIERVALUE" VARCHAR2(32 BYTE), 
	"USERID" NUMBER, 
	"OBJECTID" NUMBER, 
	"RATING" NUMBER DEFAULT NULL, 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"MODIFICATION_DATE" DATE DEFAULT sysdate, 
	"DISABLED" NUMBER(1,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_LOCALS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_LOCALS" 
   (	"LOCALID" NUMBER, 
	"ITEMID" VARCHAR2(32 BYTE), 
	"DATA" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"TYPE" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"ITEMTYPE" VARCHAR2(64 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_LOGS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_LOGS" 
   (	"LOGID" NUMBER, 
	"METHOD" VARCHAR2(32 BYTE), 
	"USERID" NUMBER DEFAULT NULL, 
	"P1" NUMBER DEFAULT NULL, 
	"P2" NUMBER DEFAULT NULL, 
	"P3" NUMBER DEFAULT NULL, 
	"P4" NUMBER DEFAULT NULL, 
	"P5" NUMBER DEFAULT NULL, 
	"P6" NUMBER DEFAULT NULL, 
	"P7" NUMBER DEFAULT NULL, 
	"TEXT" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"ERROR" NUMBER DEFAULT NULL, 
	"DURATION" FLOAT(126) DEFAULT NULL, 
	"CREATION_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 30408704 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_OBJECTS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_OBJECTS" 
   (	"OBJECTID" NUMBER, 
	"OBJECTIDENTIFIERVALUE" VARCHAR2(32 BYTE), 
	"OBJECTIDENTIFIERTYPE" VARCHAR2(8 BYTE), 
	"OBJECTTITLE" VARCHAR2(200 BYTE) DEFAULT NULL, 
	"OBJECTCONTRIBUTORS" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"OBJECTPUBLICATIONYEAR" VARCHAR2(4 BYTE) DEFAULT NULL, 
	"OBJECTMATERIALTYPE" VARCHAR2(32 BYTE) DEFAULT NULL, 
	"CREATION_DATE" DATE DEFAULT sysdate, 
	"MODIFICATION_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_REVIEWS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_REVIEWS" 
   (	"REVIEWID" NUMBER, 
	"ITEMID" VARCHAR2(32 BYTE), 
	"TITLE" VARCHAR2(32 BYTE) DEFAULT NULL, 
	"TYPE" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"DATA" VARCHAR2(4000 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_TAGS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_TAGS" 
   (	"TAGID" NUMBER, 
	"ITEMID" VARCHAR2(32 BYTE), 
	"TAG" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Table VOXB_USERS
--------------------------------------------------------

  CREATE TABLE "MKR"."VOXB_USERS" 
   (	"USERID" NUMBER, 
	"ALIAS_NAME" VARCHAR2(64 BYTE), 
	"PROFILEURL" VARCHAR2(4000 BYTE) DEFAULT NULL, 
	"USERIDENTIFIERVALUE" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"USERIDENTIFIERTYPE" VARCHAR2(16 BYTE) DEFAULT NULL, 
	"IDENTITYPROVIDER" VARCHAR2(64 BYTE) DEFAULT NULL, 
	"INSTITUTIONNAME" VARCHAR2(128 BYTE) DEFAULT NULL, 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"MODIFICATION_DATE" TIMESTAMP (6) DEFAULT sysdate, 
	"DISABLED" NUMBER(1,0) DEFAULT NULL, 
	"INSTITUTIONID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_ITEMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_ITEMS_PK" ON "MKR"."VOXB_ITEMS" ("ITEMIDENTIFIERVALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_TAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_TAGS_PK" ON "MKR"."VOXB_TAGS" ("TAGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_LOCALS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_LOCALS_IDX" ON "MKR"."VOXB_LOCALS" ("LOCALID", "DATA", "TYPE", "ITEMTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 163 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_USERS_PK" ON "MKR"."VOXB_USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_OBJECTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_OBJECTS_PK" ON "MKR"."VOXB_OBJECTS" ("OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_OBJECTS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_OBJECTS_IDX" ON "MKR"."VOXB_OBJECTS" ("OBJECTIDENTIFIERVALUE", "OBJECTIDENTIFIERTYPE", "OBJECTTITLE", "OBJECTCONTRIBUTORS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_REVIEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_REVIEWS_PK" ON "MKR"."VOXB_REVIEWS" ("REVIEWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_INS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_INS_PK" ON "MKR"."VOXB_INSTITUTIONS" ("INSTITUTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_USERS_UNIQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_USERS_UNIQ" ON "MKR"."VOXB_USERS" ("ALIAS_NAME", "PROFILEURL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 164 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_COM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_COM_PK" ON "MKR"."VOXB_COMPLAINTS" ("COMPLAINTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_LOGS_PK" ON "MKR"."VOXB_LOGS" ("LOGID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 14680064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_LOGS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_LOGS_IDX" ON "MKR"."VOXB_LOGS" ("LOGID", "METHOD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 24117248 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_ITEMS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_ITEMS_IDX" ON "MKR"."VOXB_ITEMS" ("OBJECTID", "DISABLED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_LOCALS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_LOCALS_PK" ON "MKR"."VOXB_LOCALS" ("LOCALID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_USERS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_USERS_IDX" ON "MKR"."VOXB_USERS" ("USERIDENTIFIERVALUE", "USERIDENTIFIERTYPE", "IDENTITYPROVIDER", "INSTITUTIONNAME", "DISABLED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_REVIEWS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_REVIEWS_IDX" ON "MKR"."VOXB_REVIEWS" ("REVIEWID", "TITLE", "TYPE", "DATA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 164 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_ITEMS_UNIQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "MKR"."VOXB_ITEMS_UNIQ" ON "MKR"."VOXB_ITEMS" ("USERID", "OBJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  DDL for Index VOXB_TAGS_IDX
--------------------------------------------------------

  CREATE INDEX "MKR"."VOXB_TAGS_IDX" ON "MKR"."VOXB_TAGS" ("TAGID", "ITEMID", "TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS" ;
--------------------------------------------------------
--  Constraints for Table VOXB_COMPLAINTS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_COMPLAINTS" ADD CONSTRAINT "VOXB_COM_PK" PRIMARY KEY ("COMPLAINTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("OFFENDER_INSTITUTIONID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("COMPLAINANT_USERID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("OFFENDING_ITEMID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("OFFENDER_USERID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" MODIFY ("COMPLAINTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_INSTITUTIONS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_INSTITUTIONS" ADD CONSTRAINT "VOXB_INS_PK" PRIMARY KEY ("INSTITUTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_INSTITUTIONS" MODIFY ("INSTITUTIONID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_INSTITUTIONS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_ITEMS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_ITEMS" ADD CONSTRAINT "VOXB_ITEMS_UNIQ" UNIQUE ("USERID", "OBJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_ITEMS" ADD CONSTRAINT "VOXB_ITEMS_PK" PRIMARY KEY ("ITEMIDENTIFIERVALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_ITEMS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_ITEMS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_ITEMS" MODIFY ("OBJECTID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_ITEMS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_ITEMS" MODIFY ("ITEMIDENTIFIERVALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_USERS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_USERS" ADD CONSTRAINT "VOXB_USERS_UNIQ" UNIQUE ("ALIAS_NAME", "PROFILEURL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 164 COMPUTE STATISTICS 
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_USERS" ADD CONSTRAINT "VOXB_USERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_USERS" MODIFY ("INSTITUTIONID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_USERS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_USERS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_USERS" MODIFY ("ALIAS_NAME" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_USERS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_LOGS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_LOGS" ADD CONSTRAINT "VOXB_LOGS_PK" PRIMARY KEY ("LOGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 14680064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_LOGS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_LOGS" MODIFY ("METHOD" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_LOGS" MODIFY ("LOGID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_TAGS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_TAGS" ADD CONSTRAINT "VOXB_TAGS_PK" PRIMARY KEY ("TAGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_TAGS" MODIFY ("TAG" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_TAGS" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_TAGS" MODIFY ("TAGID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_LOCALS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_LOCALS" ADD CONSTRAINT "VOXB_LOCALS_PK" PRIMARY KEY ("LOCALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_LOCALS" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_LOCALS" MODIFY ("LOCALID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_OBJECTS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_OBJECTS" ADD CONSTRAINT "VOXB_OBJECTS_PK" PRIMARY KEY ("OBJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_OBJECTS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_OBJECTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_OBJECTS" MODIFY ("OBJECTIDENTIFIERTYPE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_OBJECTS" MODIFY ("OBJECTIDENTIFIERVALUE" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_OBJECTS" MODIFY ("OBJECTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOXB_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_REVIEWS" ADD CONSTRAINT "VOXB_REVIEWS_PK" PRIMARY KEY ("REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPER_TS"  ENABLE;
  ALTER TABLE "MKR"."VOXB_REVIEWS" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "MKR"."VOXB_REVIEWS" MODIFY ("REVIEWID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOXB_COMPLAINTS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_COMPLAINTS" ADD CONSTRAINT "REF_COM_ITEMID" FOREIGN KEY ("OFFENDING_ITEMID")
	  REFERENCES "MKR"."VOXB_ITEMS" ("ITEMIDENTIFIERVALUE") ENABLE;
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" ADD CONSTRAINT "REF_COM_USERID" FOREIGN KEY ("COMPLAINANT_USERID")
	  REFERENCES "MKR"."VOXB_USERS" ("USERID") ENABLE;
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" ADD CONSTRAINT "REF_OFF_INSTITUTIONID" FOREIGN KEY ("OFFENDER_INSTITUTIONID")
	  REFERENCES "MKR"."VOXB_INSTITUTIONS" ("INSTITUTIONID") ENABLE;
  ALTER TABLE "MKR"."VOXB_COMPLAINTS" ADD CONSTRAINT "REF_OFF_USERID" FOREIGN KEY ("OFFENDER_USERID")
	  REFERENCES "MKR"."VOXB_USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOXB_ITEMS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_ITEMS" ADD CONSTRAINT "REF_ITEMS_ID" FOREIGN KEY ("OBJECTID")
	  REFERENCES "MKR"."VOXB_OBJECTS" ("OBJECTID") ENABLE;
  ALTER TABLE "MKR"."VOXB_ITEMS" ADD CONSTRAINT "REF_USER_ID" FOREIGN KEY ("USERID")
	  REFERENCES "MKR"."VOXB_USERS" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOXB_LOCALS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_LOCALS" ADD CONSTRAINT "REF_LOCALS_ITEMS_ID" FOREIGN KEY ("ITEMID")
	  REFERENCES "MKR"."VOXB_ITEMS" ("ITEMIDENTIFIERVALUE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOXB_REVIEWS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_REVIEWS" ADD CONSTRAINT "REF_REVIEWS_ITEMS_ID" FOREIGN KEY ("ITEMID")
	  REFERENCES "MKR"."VOXB_ITEMS" ("ITEMIDENTIFIERVALUE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOXB_TAGS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_TAGS" ADD CONSTRAINT "REF_TAG_ID" FOREIGN KEY ("ITEMID")
	  REFERENCES "MKR"."VOXB_ITEMS" ("ITEMIDENTIFIERVALUE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOXB_USERS
--------------------------------------------------------

  ALTER TABLE "MKR"."VOXB_USERS" ADD CONSTRAINT "REF_USERS_ID" FOREIGN KEY ("INSTITUTIONID")
	  REFERENCES "MKR"."VOXB_INSTITUTIONS" ("INSTITUTIONID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger INS_COMPLAINTS_INSTID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."INS_COMPLAINTS_INSTID_TRG" 
before insert on voxb_complaints
for each row
begin
        if :new.offender_institutionId is null then
                select institutionId
                into :new.offender_institutionId
                from voxb_institutions
                where institutionname=:new.offender_institutionName;
        end if;
        if :new.offender_institutionName is null then
                select institutionName
                into :new.offender_institutionName
                from voxb_institutions
                where institutionId=:new.offender_institutionId;
        end if;
end;
create or replace trigger ins_users_trg
before insert on voxb_users
for each row
begin
        if :new.institutionId is null then
                select institutionId
                into :new.institutionId
                from voxb_institutions
                where institutionname=:new.institutionName;
        end if;
        if :new.institutionName is null then
                select institutionName
                into :new.institutionName
                from voxb_institutions
                where institutionId=:new.institutionId;
        end if;
        end;
alter table voxb_items add (newpk number);
update voxb_items set newpk=to_number(itemidentifiervalue);
alter table voxb_complaints drop constraint ref_com_itemid;
alter table voxb_locals drop constraint ref_locals_items_id;
alter table voxb_reviews drop constraint ref_reviews_items_id;
alter table voxb_tags drop constraint ref_tag_id;
alter table voxb_items drop constraint voxb_items_pk;
alter table voxb_items drop column itemidentifiervalue;
alter table voxb_items add (itemidentifiervalue number);
update voxb_items set itemidentifiervalue=newpk;
alter table voxb_items drop column newpk;
alter table voxb_items modify (itemidentifiervalue not null);
alter table voxb_items add constraint voxb_items_pk primary key (itemidentifiervalue);

alter table voxb_complaints add (offitemidnumber number);
update voxb_complaints set offitemidnumber=to_number(offending_itemid);
alter table voxb_complaints drop column offending_itemid;
alter table voxb_complaints add (offending_itemid number);
update voxb_complaints set offending_itemid=offitemidnumber;
alter table voxb_complaints modify (offending_itemid not null);
alter table voxb_complaints drop column offitemidnumber;
alter table voxb_complaints add constraint ref_com_itemid foreign key (offending_itemid) references voxb_items (itemidentifiervalue);

alter table voxb_locals add (tmpnr number);
update voxb_locals set tmpnr=itemid;
alter table voxb_locals drop column itemid;
alter table voxb_locals add (itemid number);
update voxb_locals set itemid=tmpnr;
alter table voxb_locals modify (itemid not null);
alter table voxb_locals drop column tmpnr;
alter table voxb_locals add constraint ref_locals_items_id foreign key (itemid) references voxb_items (itemidentifiervalue) on delete cascade;

alter table voxb_reviews add (tmpnr number);
update voxb_reviews set tmpnr=itemid;
alter table voxb_reviews drop column itemid;
alter table voxb_reviews add (itemid number);
update voxb_reviews set itemid=tmpnr;
alter table voxb_reviews modify (itemid not null);
alter table voxb_reviews drop column tmpnr;
alter table voxb_reviews add constraint ref_reviews_items_id foreign key (itemid) references voxb_items (itemidentifiervalue) on delete cascade;

alter table voxb_tags add (tmpnr number);
update voxb_tags set tmpnr=itemid;
alter table voxb_tags drop column itemid;
alter table voxb_tags add (itemid number);
update voxb_tags set itemid=tmpnr;
alter table voxb_tags modify (itemid not null);
alter table voxb_tags drop column tmpnr;
alter table voxb_tags add constraint ref_tag_id foreign key (itemid) references voxb_items (itemidentifiervalue) on delete cascade;
/
ALTER TRIGGER "MKR"."INS_COMPLAINTS_INSTID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INS_USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."INS_USERS_TRG" 
before insert on voxb_users
for each row
begin
        if :new.institutionId is null then
                select institutionId
                into :new.institutionId
                from voxb_institutions
                where institutionname=:new.institutionName;
        end if;
        if :new.institutionName is null then
                select institutionName
                into :new.institutionName
                from voxb_institutions
                where institutionId=:new.institutionId;
        end if;
        end;
/
ALTER TRIGGER "MKR"."INS_USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_COMPLAINTS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_COMPLAINTS" BEFORE INSERT ON voxb_complaints FOR EACH ROW BEGIN SELECT voxb_complaints_seq.NEXTVAL INTO :NEW.complaintId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_COMPLAINTS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_ITEMS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_ITEMS" BEFORE INSERT ON voxb_items FOR EACH ROW BEGIN SELECT voxb_items_seq.NEXTVAL INTO :NEW.itemIdentifierValue FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_ITEMS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_LOCALS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_LOCALS" BEFORE INSERT ON voxb_locals FOR EACH ROW BEGIN SELECT voxb_locals_seq.NEXTVAL INTO :NEW.localId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_LOCALS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_LOGS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_LOGS" BEFORE INSERT ON voxb_logs FOR EACH ROW BEGIN SELECT voxb_logs_seq.NEXTVAL INTO :NEW.logId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_LOGS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_OBJECTS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_OBJECTS" BEFORE INSERT ON voxb_objects FOR EACH ROW BEGIN SELECT voxb_objects_seq.NEXTVAL INTO :NEW.objectId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_OBJECTS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_REVIEWS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_REVIEWS" BEFORE INSERT ON voxb_reviews FOR EACH ROW BEGIN SELECT voxb_reviews_seq.NEXTVAL INTO :NEW.reviewId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_REVIEWS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_TAGS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_TAGS" BEFORE INSERT ON voxb_tags FOR EACH ROW BEGIN SELECT voxb_tags_seq.NEXTVAL INTO :NEW.tagId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_TAGS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOXB_SEQ_USERS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MKR"."VOXB_SEQ_USERS" BEFORE INSERT ON voxb_users FOR EACH ROW BEGIN SELECT voxb_users_seq.NEXTVAL INTO :NEW.userId FROM DUAL; END;
/
ALTER TRIGGER "MKR"."VOXB_SEQ_USERS" ENABLE;
